name: Mirroring

on: [push]

jobs:
  repo-copying:
    runs-on: ubuntu-latest
    steps:
      - uses:  actions/checkout@v2
        with:
          fetch-depth: 0
      - run: ls
      - run: whoami
      - run: pwd
      