name: Mirroring

on: [push]

jobs:
  repo-copying:
    runs-on: ubuntu-latest
    steps:
      - uses:  actions/checkout@v2
        with:
          fetch-depth: 0
      - run: ls
      - run: whoami
      - run: pwd
      - run: cp -a . /home/temp
      - run: cd /home/temp
      - run: rm -fr .git
      - run: ls -a
      