name: Mirroring

on: [push]

jobs:
  repo-copying:
    runs-on: ubuntu-latest
    steps:
      - uses:  actions/checkout@v2
        with:
          fetch-depth: 0
      - run: ls
      - run: whoami
      - run: pwd
      - run: mkdir ../temp
      - run: mkdir ../temp/copy
      - run: cp -a . ../temp/copy
      - run: cd ../temp/copy
      - run: rm -fr .git
      - run: cd ..
      - run: pwd
      - uses: MrSquaare/ssh-setup-action@v1
        with:
          host: github.com
          private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - run: git clone git@github.com:IJayatharan/manual-mirroring-target.git
      - run: ls      