name: Mirroring

on: [push]

jobs:
  repo-copying:
    runs-on: ubuntu-latest
    steps:
      - uses:  actions/checkout@v2
        with:
          fetch-depth: 0
      - run: echo running on branch ${GITHUB_REF##*/}
      - run: echo ${{ github.event.head_commit.message }}
      - run: mkdir ../temp
      - run: mkdir ../temp/copy
      - run: mkdir ../temp/target
      - run: cp -a . ../temp/copy
      - run: rm -fr ../temp/copy/.git
      - run: rm -fr ../temp/copy/.github
      - uses: MrSquaare/ssh-setup-action@v1
        with:
          host: github.com
          private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - run: git clone ${{secrets.GIT_REPOSITORY_SSH_LINK}} ../temp/target/.
      - name: Remove old files from repository
        working-directory: ../temp/target
        run: rm -rfv *
      - run: cp -a ../temp/copy/. ../temp/target
      - run: git config --global user.email "indran@calcey.com"
      - run: git config --global user.name "IJayatharan"
      - name: Push code to target directory
        working-directory: ../temp/target
        run: |
          ls
          git checkout ${GITHUB_REF##*/} || git checkout -b ${GITHUB_REF##*/}
          git status
          git add .
          git commit -m "${{ github.event.head_commit.message }}" 
          git push || git push --force || git push --set-upstream origin ${GITHUB_REF##*/}