name: Mirroring

on: [push]

jobs:
  repo-copying:
    runs-on: ubuntu-latest
    steps:
      - uses:  actions/checkout@v2
        with:
          fetch-depth: 0
      - run: ls
      - run: whoami
      - run: pwd
      - run: mkdir ../temp
      - run: mkdir ../temp/copy
      - run: cp -a . ../temp/copy
      - run: cd ../temp/copy
      - run: rm -fr .git
      - run: cd ..
      - run: git clone git@github.com:IJayatharan/manual-mirroring-target.git
      - run: cp -a ./copy/. ./manual-mirroring-target
      - run: cd ./manual-mirroring-target
      - run: ls -a      