name: Mirroring

on: [push]

jobs:
  repo-copying:
    runs-on: ubuntu-latest
    steps:
      - uses:  actions/checkout@v2
        with:
          fetch-depth: 0
      - run: ls
      - run: whoami
      - run: pwd
      - run: touch test.txt
      - run: git config --global user.email "indran@calcey.com"
      - run: git config --global user.name "IJayatharan"
      - run: git status
      - run: git add .
      - run: git commit -m "test"
      - run: git push